# -*- coding: utf-8 -*-
"""Resume-Job sync engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14g12iEd4TR4BfsgurbcIhbfa4fMxMmOd
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Sample data to test
job_desc = "Looking for a Python developer with Machine Learning and SQL skills."
resume = "I am a developer who knows Python and SQL."

# The AI Logic
vectorizer = TfidfVectorizer(stop_words='english')
matrix = vectorizer.fit_transform([job_desc, resume])
score = cosine_similarity(matrix)[0][1] * 100

print(f"Match Score: {round(score, 2)}%")

# 1. Install Ngrok
!pip install pyngrok -q
from pyngrok import ngrok

# 2. Authenticate (Paste your token between the quotes)
!ngrok config add-authtoken 38WzYB6BL0Zfsj3pXtZP3ImVLVJ_3PxadrfqEFxs9RbUByTCP
# 3. Run Streamlit in the background
import subprocess
import threading
def run_streamlit():
    subprocess.run(["streamlit", "run", "app.py"])
threading.Thread(target=run_streamlit).start()

# 4. Open the Tunnel
public_url = ngrok.connect(8501)
print(f"Click this link to see your website: {public_url}")

!pip install pdfplumber -q